name: Update Phrases

on: workflow_dispatch

jobs:
  phrases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set commit account information
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Installations
        run: |
          npm ci
      - name: Decrypt credentials
        run: |
          gpg --quiet --batch --yes --passphrase="${{secrets.google_api_pw}}" \
          --output i18n/credentials.json \
          --decrypt i18n/credentials.json.gpg
      - name: Fetch and update phrases
        continue-on-error: true
        run: |
          npm run phrases
          npx prettier --write src/i18n/schema.js
          npx prettier --write src/i18n/phrases.js

          git status
          git add src/i18n/schema.js
          git add src/i18n/phrases.js
          git commit -m 'github action: update phrases' --no-verify

          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/EasyEyes/remote-calibrator
          git push
